version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - .:/app

  web:
    platform: linux/amd64  # Sau linux/arm64 dacă sistemul tău este ARM
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      GDAL_LIBRARY_PATH: "/usr/lib/x86_64-linux-gnu/libgdal.so"  # Sau /usr/lib/aarch64-linux-gnu/libgdal.so pentru ARM
      GEOS_LIBRARY_PATH: "/usr/lib/x86_64-linux-gnu/libgeos_c.so"  # Sau /usr/lib/aarch64-linux-gnu/libgeos_c.so pentru ARM

volumes:
  db_data: